### PR TITLE
Feature/pan when open

### PR DESCRIPTION
**Pull request by chourobin**
Added a panning mode that enables panning on the center view controller when the side menu is in the "open" state.

### CODE REVIEW

**Comment by mikefrederick** [comment]
Do you know that you can already pan the center view controller when the menus are open? Not sure if I follow the intention here.

**Comment by chourobin** [comment]
Oops, my mistake, I didn't know that was supported.  Feel free to reject/close this PR.

**Comment by chourobin** [comment]
My intention was to have panning disabled when the menu is closed and only allow panning to close the menu once the menu was open.  Is that currently possible?

**Comment by mikefrederick** [comment]
Yeah it is, you would have to either listen for a state change event or use a block like so:

``` objective-c
container.panMode = MFSideMenuPanModeSideMenu;
[container setMenuState:MFSideMenuStateLeftMenuOpen completion:^{
    container.panMode = MFSideMenuPanModeSideMenu|MFSideMenuPanModeCenterViewController;
}];
```

That being the case, I am going to close this.

**Pull request closed without merging**
