### PR TITLE
Added a convenience method to allow access to MFMenuContainerViewController

### PR DESCRIPTION
**Pull request by chourobin**
Hi, great work on sidemenu.

I added a category that allows for convenient access to the MFMenuContainerViewController. It is similar to the way ViewDeck has self.viewDeckController.

Let me know if this is okay.

### CODE REVIEW

**Comment by ghost** [comment]
awesome. thanks!

**Comment by mourlamstudios** [comment]
Fantastic work here. le-git.

**Comment by mikefrederick** [comment]
Cool, thanks for the contribution.

Before I merge, can you move the UIViewController category into it's own file instead of placing the code in the container's file?

**Comment by chourobin** [comment]
Done! Thanks for this library by the way.

**Comment by mikefrederick** [comment]
Merged. Thanks again for the contribution.

**Pull request merged**
