### PR TITLE
Async slide in (like Wunderlist 2)

### PR DESCRIPTION
**Pull request by kasperpihl**
Hi, I added a small property called asyncSlideFactor.
Setting this to etc. 3 gives the effect like the Wunderlist 2 menu.
Thank you very much for a nice and easy-to-use code, hope you can use this so I can use your pod instead ;-)
Kasper

### CODE REVIEW

**Comment by mikefrederick** [comment]
I like the idea, but the implementation isn't complete.

The first time you try opening the menu using a bar button item the menus don't slide in.

**Comment by kasperpihl** [comment]
That issue should be fixed now.

**Comment by mikefrederick** [comment]
I took your code, did a bit of refactoring, and implemented this idea. It's in the most recent version of the repo.

You want to set `menuSlideAnimationEnabled = YES` and adjust the `menuSlideFactor` to alter the exaggeration of the side menu slide.

Cheers, let me know how it works for you.

**Comment by kasperpihl** [comment]
That's great. Thanks.

**Pull request closed without merging**
